### ISSUE TITLE
Apparent Crash due to the magma zombie's sword or the magma zombie himself causing the server to error

### ISSUE THREAD

**Issue by Darkmega18** [mcpecommander/Mobultion-mod#17]
A few of my players have told me of the magma zombie causing issues with a ticking entity crash of some kind. I have a feeling it's either related to his water damage or lava spawning. so for now I've turned him right down so he's got nowhere to spawn and stuff until you have a look at this. this is the segment of console or crash that the player sent to me.

[11:03:58] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_161]
        at mcpecommander.mobultion.entity.entities.zombies.EntityMagmaZombie.func_70652_k(EntityMagmaZombie.java:142) ~[EntityMagmaZombie.class:?]
        at mcpecommander.mobultion.entity.entityAI.zombiesAI.EntityAIKnightAttackMelee.checkAndPerformAttack(EntityAIKnightAttackMelee.java:208) ~[EntityAIKnightAttackMelee.class:?]
        at mcpecommander.mobultion.entity.entityAI.zombiesAI.EntityAIKnightAttackMelee.func_75246_d(EntityAIKnightAttackMelee.java:193) ~[EntityAIKnightAttackMelee.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) ~[ade.class:?]
        at mcpecommander.mobultion.entity.entities.zombies.EntityAnimatedZombie.func_70636_d(EntityAnimatedZombie.java:226) ~[EntityAnimatedZombie.class:?]
        at mcpecommander.mobultion.entity.entities.zombies.EntityMagmaZombie.func_70636_d(EntityMagmaZombie.java:91) ~[EntityMagmaZombie.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) ~[ade.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[11:03:58] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Game Servers\Transcendence\.\crash-reports\crash-2018-08-06_11.03.58-server.txt

**Comment by mcpecommander** [comment]
It is the fire randomness effect, I fixed it but I did not release the fix yet. I waiting on some api fixes. Turn off the magma zombie spawn rates for now (using the biome changing stick)

**Comment by Darkmega18** [comment]
I just took the biomes out of his config and set him to weight 1 and max and min 1 so he's got nowhere to spawn. also turned off his true and false features incase he does somehow magically show up.

**Comment by mcpecommander** [comment]
You don't need to turn off his configs unless somebody has creative mode access and even if somebody summoned him some other way, it will crash at random when attacking. The weight however should be set to 0,0 min max but that does not matter since it does not have spawn biomes

**Comment by Darkmega18** [comment]
ah, I got paranoid about spontaneous crashings, since in the configs you say the mins are 1 for any given weight values etc. :P

**Comment by mcpecommander** [comment]
I have not touch modded minecraft in 3 months so I might be wrong about the min and max but you did it right, do not worry.

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
