### ISSUE TITLE
Gardener Enderman Crashing with Lack of Flowers

### ISSUE THREAD

**Issue by FallenEagle1** [mcpecommander/Mobultion-mod#21]
Forge: 14.23.5.2777
Mobultion: 0.4.5

Had a flat world, so probably didn't have any flowers in it, and received this crash. This looks to be similar to  #9, just a slight change in the stack trace.

```
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 8
	at net.minecraft.block.Block.canSustainPlant(Block.java:1706)
	at mcpecommander.mobultion.entity.entityAI.endermenAI.EntityAIGardenerMoveToFlower.hasCrops(EntityAIGardenerMoveToFlower.java:196)
	at mcpecommander.mobultion.entity.entityAI.endermenAI.EntityAIGardenerMoveToFlower.func_179488_a(EntityAIGardenerMoveToFlower.java:157)
```

https://pastebin.com/rX2P5Maw

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
