### ISSUE TITLE
Server error-cannot generate some entity

### ISSUE THREAD

**Issue by Huaxidesu** [mcpecommander/Mobultion-mod#22]
[Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
        at net.minecraft.entity.EntityLiving.setGoalTarget(EntityLiving.java:193) [vq.class:?]
        at net.minecraft.entity.EntityLiving.setAttackTarget(EntityLiving.java:183) [vq.class:?]
        at mcpecommander.mobultion.entity.entityAI.zombiesAI.EntityAIDoctorTarget.startExecuting(EntityAIDoctorTarget.java:60) [EntityAIDoctorTarget.class:?]
        at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(EntityAITasks.java:75) [xf.class:?]
        at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:823) [vq.class:?]
        at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2685) [vp.class:?]
        at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:626) [vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:46) [ade.class:?]
        at mcpecommander.mobultion.entity.entities.zombies.EntityAnimatedZombie.onLivingUpdate(EntityAnimatedZombie.java:226) [EntityAnimatedZombie.class:?]
        at mcpecommander.mobultion.entity.entities.zombies.EntityDoctorZombie.onLivingUpdate(EntityDoctorZombie.java:129) [EntityDoctorZombie.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2503) [vp.class:?]
        at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:335) [vq.class:?]
        at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:51) [ade.class:?]
        at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2296) [amu.class:?]
        at net.minecraft.world.World.updateEntity(World.java:2250) [amu.class:?]
        at net.minecraft.world.World.redirect$updateEntity$zzp000(World.java:4463) [amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:2024) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:830) [oo.class:?]
        at fr.uranoscopidae.hatedmobs.common.FalsifiedWorldServer.updateEntities(FalsifiedWorldServer.java:617) [FalsifiedWorldServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:780) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
